spring.application.name=conge-service

server.port=8084

spring.cloud.config.enabled=false

# Eureka configuration
#eureka.client.service-url.defaultZone=http://bank-registry-service:8761/eureka/
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# spring.datasource.url = jdbc:postgresql://postgres-db:5432/conge_db
spring.datasource.url = jdbc:postgresql://localhost:5432/conge_db
spring.datasource.username=prosper
spring.datasource.password=prosper
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# spring.rabbitmq.host=rabbitmq-broker
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Configuration de base de Springdoc
springdoc.swagger-ui.path=/swagger-ui.html

# Informations générales sur l'API (ce qui apparaît en haut de la page Swagger)
springdoc.info.title=ERP Project API - Conge Service
springdoc.info.version=1.0.0
springdoc.info.description=Documentation des routes du microservice de gestion des conges et RH.
