server {
    listen 8080;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # Proxy vers ton backend si besoin :
    # location /api/ {
    #     proxy_pass http://bank-gateway-service:8000;
    # }
}

