services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prosper
      POSTGRES_PASSWORD: prosper
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - erp_employe_data:/var/lib/postgresql/data
    networks:
      - erp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prosper"]
      interval: 25s
      timeout: 25s
      retries: 5
      start_period: 60s

  bank-config-service:
    build: ./bank_config_service
    container_name: bank-config-service
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: bank-config-service
      SERVER_PORT: 8080
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/banking-project-chenjo/cloud-conf.git
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: main
    networks:
      - erp-network
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://bank-config-service:8080/actuator/health"]
      interval: 25s
      timeout: 25s
      retries: 5
      start_period: 60s

  bank-registry-service:
    build: ./bank-registry-service
    container_name: bank-registry-service
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: bank-registry-service
      SERVER_PORT: 8761
      SPRING_CLOUD_CONFIG_URI: http://bank-config-service:8080
      SPRING_CONFIG_IMPORT: optional:configserver:http://bank-config-service:8080
    depends_on:
      bank-config-service:
        condition: service_healthy
    networks:
      - erp-network
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://bank-registry-service:8761/actuator/health",
        ]
      interval: 25s
      timeout: 25s
      retries: 5
      start_period: 60s

  bank-gateway-service:
    build: ./bank-gateway-service
    container_name: bank-gateway-service
    ports:
      - "8001:8001"
    environment:
      SPRING_APPLICATION_NAME: bank-gateway-service
      SERVER_PORT: 8001
      SPRING_CLOUD_CONFIG_URI: http://bank-config-service:8080
      SPRING_CONFIG_IMPORT: optional:configserver:http://bank-config-service:8080
    depends_on:
      bank-config-service:
        condition: service_healthy
      bank-registry-service:
        condition: service_healthy
    networks:
      - erp-network

  rabbitmq-broker:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-broker
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - erp-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 25s
      timeout: 25s
      start_period: 60s
      retries: 5

  employe-service:
    build: ./employer-service
    container_name: employer-service
    ports:
      - "8085:8085"
    environment:
      SPRING_APPLICATION_NAME: employer-service
      SERVER_PORT: 8085
      SPRING_CLOUD_CONFIG_URI: http://bank-config-service:8080
      SPRING_CONFIG_IMPORT: optional:configserver:http://bank-config-service:8080
    depends_on:
      bank-config-service:
        condition: service_healthy
      bank-registry-service:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
      rabbitmq-broker:
        condition: service_healthy
    networks:
      - erp-network

  conge-service:
    build: ./conge-service
    container_name: conge-service
    ports:
      - "8084:8084"
    environment:
      SPRING_APPLICATION_NAME: conge-service
      SERVER_PORT: 8084
      SPRING_CLOUD_CONFIG_URI: http://bank-config-service:8080
      SPRING_CONFIG_IMPORT: optional:configserver:http://bank-config-service:8080
    depends_on:
      bank-config-service:
        condition: service_healthy
      bank-registry-service:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
      rabbitmq-broker:
        condition: service_healthy
    networks:
      - erp-network

  tache-service:
    build: ./tache-service
    container_name: tache-service
    ports:
      - "8086:8086"
    environment:
      SPRING_APPLICATION_NAME: tache-service
      SERVER_PORT: 8086
      SPRING_CLOUD_CONFIG_URI: http://bank-config-service:8080
      SPRING_CONFIG_IMPORT: optional:configserver:http://bank-config-service:8080
    depends_on:
      bank-config-service:
        condition: service_healthy
      bank-registry-service:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
      rabbitmq-broker:
        condition: service_healthy
    networks:
      - erp-network

  authentification-service:
    build: ./authentification-service
    container_name: authentification-service
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_HOST: rabbitmq-broker
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      DATABASE_URL: postgres://hrh_user:hrh-password@postgres-db:5432/authentification_db
      SECRET_KEY: "django-insecure-%8vd1xfb4$+kj^of*s2dk-y86x(!f7r+wq%zb(-dpb&b=5e0&o"
      DEBUG: "True"
      CONFIG_SERVER_URL: http://bank-config-service:8080
      EUREKA_SERVER: http://bank-registry-service:8761/eureka
      SERVICE_NAME: authentification-service
      PORT: "8000"
      PROFILE: dev
    depends_on:
      bank-config-service:
        condition: service_healthy
      bank-registry-service:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
      rabbitmq-broker:
        condition: service_healthy

    networks:
      - erp-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/"]
      interval: 25s
      timeout: 25s
      retries: 5
      start_period: 60s

networks:
  erp-network:
    driver: bridge

volumes:
  erp_employe_data:
